import * as fs from 'node:fs';
import * as path from 'node:path';
import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import * as dotenv from 'dotenv';
import request from 'supertest';
import { App } from 'supertest/types';
import { beforeEach, describe, expect, it } from 'vitest';
import { LLMService } from './../src/ai/llm.service';
import { AppModule } from './../src/app.module';
import { MockLLMService } from './mocks/llm.service';

// Load the Testcontainers env file generated by globalSetup
const envPath = path.resolve(__dirname, '../../.env.e2e.test');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath, override: true });
}
describe('AppController (e2e)', () => {
  let app: INestApplication<App>;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(LLMService)
      .useClass(MockLLMService)
      .compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/api/v1 (GET)', () => {
    return request(app.getHttpServer()).get('/api/v1').expect(200).expect('Hello World!');
  });

  it('/api/v1/health (GET)', async () => {
    const res = await request(app.getHttpServer() as App)
      .get('/api/v1/health')
      .expect(200);
    expect(res.body.status).toBe('UP');
  });
});
