import * as fs from 'node:fs';
import * as path from 'node:path';
import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import * as dotenv from 'dotenv';
import { Pool } from 'pg';
import request from 'supertest';
import { App } from 'supertest/types';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { LLMService } from './../src/ai/llm.service';
import { AppModule } from './../src/app.module';
import { PG_POOL } from './../src/database/database.module';
import { DatabaseService } from './../src/database/database.service';
import { MockLLMService } from './mocks/llm.service';

// Load the Testcontainers env file generated by globalSetup
const envPath = path.resolve(__dirname, '../../.env.e2e.test');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath, override: true });
}

describe('Database Integration (e2e)', () => {
  let app: INestApplication;
  let dbService: DatabaseService;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(LLMService)
      .useClass(MockLLMService)
      .compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    dbService = app.get<DatabaseService>(DatabaseService);
  });

  afterAll(async () => {
    if (app) {
      // Manually close database pool to prevent Vitest from hanging
      const pool = app.get<Pool>(PG_POOL);

      if (pool) {
        await pool.end();
      }

      await app.close();
    }
  });

  it('/api/v1/health (GET) - status should be UP and return valid db results from testcontainers', async () => {
    const response = await request(app.getHttpServer() as App)
      .get('/api/v1/health')
      .expect(200);

    const body = response.body;

    expect(body.status).toBe('UP');
    expect(body.database.postgres).toBeInstanceOf(Array);
    expect(body.database.postgres[0]).toMatchObject({ val: 1 });
  });

  it('can fetch PostgreSQL table names with DatabaseService against testcontainers', async () => {
    // Tests dummy wait_time tables in Postgres global-setup
    const tables = await dbService.getAllTableNames();
    expect(tables).toContain('dummy_kpi');
  });

  it('can get PostgreSQL schema via DatabaseService against testcontainers', async () => {
    const schema = await dbService.getTableSchema('dummy_kpi');
    expect(schema.length).toBeGreaterThanOrEqual(2);
    expect(schema.map((r) => r[0])).toContain('id');
    expect(schema.map((r) => r[0])).toContain('name');
  });

  it('can execute valid SQL query against testcontainers PostgreSQL', async () => {
    const result = await dbService.validateSql('SELECT 1 as val');
    expect(result.valid).toBe(true);
  });
});
